mappings:
  - driveFolderId: "1n8FX9B0sfIsRys2LmppqY5idkIXqtydI"
    destination:
      provider: "local"
      path: "./backups/a"
      prefix: "docs"
rename:
  - from: "(利用者非公開)利用者向けAIナレッジ"
    to: "implicit-ai-knowledge"
  - from: "あばばば"
    to: "ababa"